### ISSUE TITLE
multiple-maps branch does not work on Ionic 2.0 rc0

### ISSUE THREAD

**Issue by adrinavarro** [mapsplugin/v2.0-demo#6] opened 2016-10-07 14:33 UTC
We've created a test app with Ionic 2.0 rc0 and the new branch does not work in that app.

Here's the source for said app: https://github.com/ZiFFeL1992/maps-v2
An example video: https://sendvid.com/23m9ynbu

What happens is that interactions (touch events) are not recognized. This does not happen in the test APK provided, just on Ionic 2.0 rc0.

**Comment by wf9a5m75** [comment] 2016-10-07 17:00
The problem is ionic places a &lt;div&gt; over the map area.
![screen shot 2016-10-07 at 9 50 54 am](https://cloud.githubusercontent.com/assets/167831/19198583/c04df1bc-8c74-11e6-9822-687b6f212e5d.png)

![screenshot_20161007-095220](https://cloud.githubusercontent.com/assets/167831/19198592/ca43d77c-8c74-11e6-9815-62ac8a4886dd.png)

If I remove the z-index  from CSS, the map is touchable.

I need to adjust the JS later.

**Comment by mickadoua** [comment] 2016-10-07 19:02
i have same problem, i remove Z-index and this dont fixe the issue,

i have one question,
do we need add  method on googlemaps.d.ts? 
 like this : 
    `setCameraTarget(location: CameraPosition): any;`

**Comment by wf9a5m75** [comment] 2016-10-07 20:23
What is `googlemaps.d.ts`?

**Comment by wf9a5m75** [comment] 2016-10-07 20:27
And if you want to change the camera position, you can use `map.animateCamera(cameraPosition)` and `map.moveCamera(cameraPosition)`.
That's are the same as v1.

**Comment by ZiFFeL1992** [comment] 2016-10-07 20:55
That file doesn't affect the repo we shared with you, it's just a wrapper: https://github.com/driftyco/ionic-native

**Comment by wf9a5m75** [comment] 2016-10-07 20:59
What?

**Comment by wf9a5m75** [comment] 2016-10-07 21:01
@ZiFFeL1992 I don't understand what are you talking about. I'm not familiar with ionic.

**Comment by wf9a5m75** [comment] 2016-10-07 21:03
@mickadoua 
>i have the same problem, i removed Z-index and this dont fixe the issue,

After removing the z-index, try to rotate your phone.

**Comment by ZiFFeL1992** [comment] 2016-10-07 21:11
1. `git pull`
2. `npm i`

You shouldn't find that file anymore.

**Comment by wf9a5m75** [comment] 2016-10-07 21:13
Ah, I see. You updated your project to remove the ionic-native.

**Comment by ZiFFeL1992** [comment] 2016-10-07 21:14
Yup, but doesn't matter as I wasn't using the wrapper with the plugin, just calling it like you would do without ioinc :)

**Comment by wf9a5m75** [comment] 2016-10-08 08:51
![capture](https://cloud.githubusercontent.com/assets/167831/19211781/b37dc694-8cf9-11e6-8601-0cec2acfbdd9.gif)

https://dl.dropboxusercontent.com/u/1456061/cordova-google-maps/v2/ZiFFeL1992_maps-v2-fixed.apk

**Comment by wf9a5m75** [comment] 2016-10-08 08:52
I fixed the JS bug. Reinstall the multiple-maps branch should solve the ionic touch problem.

**Comment by ZiFFeL1992** [comment] 2016-10-08 21:49
Will check it next week, thanks!

**Comment by mickadoua** [comment] 2016-10-09 22:40
the touch event work well, 
but 2 news errors, 

1) 
the multi map doesn't work ?, i have 2 pages with the map, and the last page was blank 

2) and i have multiple error like this
```
main.js:65180 Uncaught TypeError: Cannot read property 'apply' of undefined

callInstance @ main.js:65180(anonymous function) @ main.js:65191value @ main.js:65378(anonymous function) @ main.js:80089SafeSubscriber.__tryOrUnsub @ main.js:6777SafeSubscriber.next @ main.js:6726Subscriber._next @ main.js:6679Subscriber.next @ main.js:6643listener @ BaseClass.js:55BaseClass.self.trigger @ BaseClass.js:43(anonymous function) @ Map.js:140t.invokeTask @ polyfills.js:3onInvokeTask @ main.js:7368t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
12main.js:80098 onClick
```

here the Repo 
https://github.com/mickadoua/pocMapV2

**Comment by wf9a5m75** [comment] 2016-10-09 22:51
@mickadoua Please try to save my time.

Please make the apk of your project. Building apk is spending my time a lot.

And regarding of the js error, please identify the position of the JS error.
All source code is open.

**Comment by wf9a5m75** [comment] 2016-10-10 07:11
@mickadoua  The ionic google maps plugin is not my product. So I don't (can't) support it, since I'm not familiar with ionic.
And several event names and methods are changed.
It means you need to modify your code.

At least, I worked your app. (No more help for your code)

```js
        this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => {
            console.log('map ready');
            //this.map.setCenter(location);
            this.map.setCameraTarget(position);
            //this.map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe(() => {
            //    console.log('map change');
            //});
        });
```
![capture](https://cloud.githubusercontent.com/assets/167831/19228849/dd138e50-8e7d-11e6-91ac-1ca8c11228c7.gif)

**Comment by mickadoua** [comment] 2016-10-10 22:01
ok thank you @wf9a5m75 i will run another project from scratch

**Comment by ZiFFeL1992** [comment] 2016-10-12 20:47
Okay, I have just update the repo, here i'll try to describe the issues I've found:

1. If you go to home tab you won't be able to see the map until you tap on the screen, this happens after adding `animateCamera` event.

2. `padding` is mandatory inside `animateCamera`, the app crashes if I don't add this parameter to that event config, why?

3. You should be able to tap on a marker, when you go to a subpage from the map, the map on the tab gets destroyed, why? I'm not calling `map.remove()`.

4. I'm unable to see map on subpages (Modal / SubPage) unless I modify class `.app-root` adding `visibility: hidden` to it, this should be a common use, having one map always available on any tab and then another map on a subpage that could be dynamically created.

5. I can't confirm yet but seems like adding lots of markers works slower than with master branch.

**Comment by wf9a5m75** [comment] 2016-10-12 21:05
Quick reply:

>1. Can not see the map when you change the tab until tapping.

In that case, you need to fire the `touch_start` event.
```js
cordova.fireDocumentEvent('touch_start', {});
```
Please understand how the plugin works.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

>2. padding is specified mandatory

The padding property is specified even in the v1.
But I don't provide the way to modify the value.
In the v2, if you don't specify the padding, the value is 20px (same as v1).
If you don't want to specify the padding, just give 0.

>3. The map is destroyed.

Because when you change the tab, the map div is removed automatically by browser.
Where should I move to the mapview?
That's why if the map div is removed, the map is also removed automatically.

> 4. having common map.

You need to adjust your code or css (etc...) for your purpose.
I don't support specific JS framework.

> 5. the v2-beta is slow for adding lots of markers?

If you feel so, you can use the v1.

**Comment by ZiFFeL1992** [comment] 2016-10-12 21:29
> 2 padding is specified mandatory

Doc related?


> 3 The map is destroyed.

It doesn't get destroyed when you change between tabs, only when you pushing to a subpage **from the map** tab, but the code that creates the map in a tab stays until you close the app, so it's always available. You can try to go to Home, then go back to about, push the modal, press android hardware button back and go again to the map, will be there. But if you go to the subpage from the map it gets destroyed.


> 4 having common map.

Maybe the map layer should always be at the bottom of the page / layer, I don't know how it works internally or if it's possible.

**Comment by wf9a5m75** [comment] 2016-10-12 21:31
If you want to have common map, `map.setDiv(null)` when you change the tab.
This might be help. (I'm not cofirmed)

**Comment by wf9a5m75** [comment] 2016-10-12 21:36
> camera padding

You can specify the `padding` property for the camera parameter.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Circle/setRadius.html#L50

The padding property is available for `getMap()`, `setOptions()`, `moveCamera`, and `animateCamera()` methods.

Documents are not yet for all methods. Please check the demo apk file carefully. You might find out new options.

**Comment by ZiFFeL1992** [comment] 2016-10-12 21:38
I don't want a common map, I'd like to use one 'static' map in a tab and create/destroy another map on subpages, I just need a way to avoid map (in the tab) being destroyed , DOM changes because a new page is injected, but that **doesn't** mean that the div gets destroyed on that change.

You can easily check this in the chrome console.

**Comment by wf9a5m75** [comment] 2016-10-12 21:42
The test APK please.
I need to work on my real job. So please help to save my time.

**Comment by Hirbod** [comment] 2016-10-13 01:51
I think he wants to know a way to prevent that the plugin automatically destroy a map - did I get that right?

**Comment by wf9a5m75** [comment] 2016-10-13 02:07
I know. But I have tons of things to do for plugin.
That's why I ask providing an apk (and describe picture or video).
Building apk spends my time.

**Comment by ZiFFeL1992** [comment] 2016-10-13 09:25
https://drive.google.com/file/d/0BzzwDw5jEO0xVWdZSWM4ZmNOX1k/view?usp=sharing

Steps:
1. Go to Home tab
2. Click to see the map (need to test touch_start)
3. Click on the marker
4. Click on the info window
5. Behind the scenes the new map is available (need to fix css to bring it to the front) and the one from the home tabs gets destroyed without calling map.remove(), and the div is in the DOM **always**.


https://drive.google.com/file/d/0BzzwDw5jEO0xZFBYMndFYUY3VGs/view?usp=sharing

Steps:
1. Go to Home tab
2. Click to see the map
3. Go back to About tab
4. Open the modal
5. Press back button to close the modal
6. Go to Home tab
7. The map is available :)

**Comment by ZiFFeL1992** [comment] 2016-10-13 09:59
Now I'm working with https://github.com/mapsplugin/cordova-plugin-googlemaps.git#52e6b9b30dcfbee969a1313aed13627a6ea3a33e

Video: https://drive.google.com/open?id=0BzzwDw5jEO0xRGFhWWpBZkoyYVk

3 comments:
1. I can see the map in a subpage.
2. When calling map.remove() the map doesn't disappear, also the app crashes.
3. The map in the tab still available even after going to a subpage (before gets destroyed).

**Comment by wf9a5m75** [comment] 2016-10-13 14:10
Thank you.  Since I just wake up now, I will check the videos.
And please provide APK files in order to inspect them.
Only videos, I can not do anything.

**Comment by ZiFFeL1992** [comment] 2016-10-13 14:35
First case and second case: https://drive.google.com/open?id=0BzzwDw5jEO0xWXVtd29ZQWQ2Umc

Third case: https://drive.google.com/open?id=0BzzwDw5jEO0xazF0ck9hSUl4eWc

**Comment by wf9a5m75** [comment] 2016-10-13 20:13
Ok, I finally understand what you talking about.
You use the maps plugin with **incorrect way**.

What happen in your app is the below image.

You are trying a map over the another map.
This way is not supported in current the maps v2-beta, **because the plugin can not decide which map should receive the touch event.**

![device-2016-10-13-123910](https://cloud.githubusercontent.com/assets/167831/19365143/2ff65e7a-9146-11e6-8905-d74aebbe0dba.png)

I wish support this way, but not yet.

**Comment by samedii** [comment] 2016-11-07 11:35
I had no troubles with the latest version of v2 and ionic. Is this sitll an issue?

**Comment by wf9a5m75** [comment] 2016-11-07 17:51
Yeah, I waited almost one month, but never got new update.
I close this issue.

**Closed by wf9a5m75** 2016-11-07 17:51 UTC
