### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by gynekolog** [mapsplugin/v2.0-demo#12] opened 2016-10-24 09:33 UTC
I get error message in console:

`Failed to execute 'getComputedStyle' on 'Window': parameter is not of type 'Element'`

This happened after update to latest version, previous version was OK.

App run on Ionic 1.3.1
Phone: Nexus 5
Android: 7
WebView: 55.0.2883.18

source (without map plugin): https://www.dropbox.com/s/cygmmdxikhhp535/myApp.zip?dl=0

**Comment by gynekolog** [comment] 2016-10-24 11:06
If add
`console.log(dom)`
to line 264 at cordova-plugin-googlemaps/www/Common.js result is
![screen shot 2016-10-24 at 13 00 36](https://cloud.githubusercontent.com/assets/4593089/19643388/51457460-99ea-11e6-94a3-3e59321df49e.png)

so I comment line 265-267 (of original file)
```
/*if (isNaN(z)) {
        return getZIndex(dom.parentNode);
   }*/
```
and plugin works fine.

**Comment by wf9a5m75** [comment] 2016-10-24 14:11
Thank you for the report. I will check it later.
Getting zIndex is important for the plugin to detect the touch correctly.

I think `if (isNaN(z) && z !== document) {` should solve the problem, but I will check it later.

**Comment by wf9a5m75** [comment] 2016-10-25 17:22
Sorry for late. I investigated your code, but I could not reproduce the issue.
However, I modified the code to prevent the issue.
So the issue should be solved.

And I noticed that the ionic sets the `display:none` when I changed the tab page.
Regarding of this, the plugin removes the map automatically.
I fixed this issue also.

Please reinstall the plugin and try it, then report to me.
Thanks.

![issue_12](https://cloud.githubusercontent.com/assets/167831/19696653/f2db47c0-9a9c-11e6-97ea-4462dd59a83d.gif)

**Comment by wf9a5m75** [comment] 2016-10-27 18:46
@gynekolog 

I reproduced this issue yesterday, and I modified the code.
Please reinstall the plugin and try again, then let me know the result.
Thanks.

**Comment by wf9a5m75** [comment] 2016-11-10 23:05
I close this issue because I waited almost one month, but no updated.
And this issue has been already fixed.

**Closed by wf9a5m75** 2016-11-10 23:05 UTC
