### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by mickadoua** [mapsplugin/v2.0-demo#8] opened 2016-10-07 20:51 UTC
after few minute my app crash and here the logcat

```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ionicframework.pocmapv2425992, PID: 21104
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'float android.graphics.RectF.width()' on a null object reference
                                                       at plugin.google.maps.MyPluginLayout$ResizeTask$1.run(MyPluginLayout.java:100)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:155)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
10-07 22:37:11.749 693-1743/? E/ActivityManager: App crashed! Process: com.ionicframework.pocmapv2425992
```

**Comment by wf9a5m75** [comment] 2016-10-07 20:54
Please provide an example project that reproduce your problem certainly.
And providing video, apk file are also appreciated.

**Comment by gynekolog** [comment] 2016-10-11 11:22
I have this error too. You must set size of map by css. Width can be set in % but height must be in px.

```
#map_canvas {
  width: 100%;
  height: 400px;
  position: relative;
}
```

source: https://github.com/mapsplugin/v2.0-demo/issues/3#issuecomment-251730199

**Comment by wf9a5m75** [comment] 2016-10-11 14:10
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/For-ionic2-users


No source code, no help

**Comment by wf9a5m75** [comment] 2016-10-11 16:42
@gynekolog You need to `map.remove()` before the new tab is open.
Because the map div is removed when the map tab is closed.

**Comment by wf9a5m75** [comment] 2016-10-11 20:47
@gynekolog I updated the js code. The map is removed automatically when the mapDiv is removed.
Please reinstall the plugin from repository, and try again.

**Comment by wf9a5m75** [comment] 2016-11-10 23:04
I close this issue because I waited almost one month, but no updated.

**Closed by wf9a5m75** 2016-11-10 23:04 UTC
